NguyenVanHuu0736/Models/ErrorViewModel.cs
namespace NguyenVanHuu0736.Models;
public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

NguyenVanHuu0736/Models/NVHStudent.cs
using System.ComponentModel.DataAnnotations;

namespace NguyenVanHuu0736.Models;
public class NVHStudent
{
    [Key]
    public string? NVHStudentId { get; set; }

    
    public string? NVHStudentName { get; set; }

   
    public string? NVHStudentDIACHI { get; set; }


}

NguyenVanHuu0736/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NguyenVanHuu0736.Models;

namespace NguyenVanHuu0736.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
// HỮU1921050736
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

NguyenVanHuu0736/Controllers/NVHStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NguyenVanHuu0736.Models;

namespace NguyenVanHuu0736.Controllers
{
    public class NVHStudentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NVHStudentController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: NVHStudent
        public async Task<IActionResult> Index()
        {
              return _context.NVHStudent != null ? 
                          View(await _context.NVHStudent.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.NVHStudent'  is null.");
        }

        // GET: NVHStudent/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.NVHStudent == null)
            {
                return NotFound();
            }

            var nVHStudent = await _context.NVHStudent
                .FirstOrDefaultAsync(m => m.NVHStudentId == id);
            if (nVHStudent == null)
            {
                return NotFound();
            }

            return View(nVHStudent);
        }

        // GET: NVHStudent/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NVHStudent/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NVHStudentId,NVHStudentName,NVHStudentDIACHI")] NVHStudent nVHStudent)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nVHStudent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nVHStudent);
        }

        // GET: NVHStudent/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.NVHStudent == null)
            {
                return NotFound();
            }

            var nVHStudent = await _context.NVHStudent.FindAsync(id);
            if (nVHStudent == null)
            {
                return NotFound();
            }
            return View(nVHStudent);
        }

        // POST: NVHStudent/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("NVHStudentId,NVHStudentName,NVHStudentDIACHI")] NVHStudent nVHStudent)
        {
            if (id != nVHStudent.NVHStudentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nVHStudent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NVHStudentExists(nVHStudent.NVHStudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nVHStudent);
        }

        // GET: NVHStudent/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.NVHStudent == null)
            {
                return NotFound();
            }

            var nVHStudent = await _context.NVHStudent
                .FirstOrDefaultAsync(m => m.NVHStudentId == id);
            if (nVHStudent == null)
            {
                return NotFound();
            }

            return View(nVHStudent);
        }

        // POST: NVHStudent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.NVHStudent == null)
            {
                return Problem("Entity set 'ApplicationDbContext.NVHStudent'  is null.");
            }
            var nVHStudent = await _context.NVHStudent.FindAsync(id);
            if (nVHStudent != null)
            {
                _context.NVHStudent.Remove(nVHStudent);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NVHStudentExists(string id)
        {
          return (_context.NVHStudent?.Any(e => e.NVHStudentId == id)).GetValueOrDefault();
        }
    }
}

NguyenVanHuu0736/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NguyenVanHuu0736/Views/NVHStudent/Create.cshtml
@model NguyenVanHuu0736.Models.NVHStudent

@{
    ViewData["Title"] = "Create";
}

<h1>THÊM</h1>

<h4>NVHStudent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NVHStudentId" class="control-label">MÃ </label>
                <input asp-for="NVHStudentId" class="form-control" />
                <span asp-validation-for="NVHStudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NVHStudentName" class="control-label">TÊN</label>
                <input asp-for="NVHStudentName" class="form-control" />
                <span asp-validation-for="NVHStudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NVHStudentDIACHI" class="control-label">ĐỊA CHỈ</label>
                <input asp-for="NVHStudentDIACHI" class="form-control" />
                <span asp-validation-for="NVHStudentDIACHI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="THÊM" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay Lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NguyenVanHuu0736/Views/NVHStudent/Delete.cshtml
@model NguyenVanHuu0736.Models.NVHStudent

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa</h1>

<h3>Bạn có chắc chắn muốn xóa không?</h3>
<div>
    <h4>NVHStudent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NVHStudentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NVHStudentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NVHStudentDIACHI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NVHStudentDIACHI)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NVHStudentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NguyenVanHuu0736/Views/NVHStudent/Details.cshtml
@model NguyenVanHuu0736.Models.NVHStudent

@{
    ViewData["Title"] = "Details";
}

<h1>CHI TIẾT</h1>

<div>
    <h4>NVHStudent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NVHStudentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NVHStudentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NVHStudentDIACHI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NVHStudentDIACHI)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.NVHStudentId">CHỈNH SỬA</a> |
    <a asp-action="Index">Back to List</a>
</div>

NguyenVanHuu0736/Views/NVHStudent/Edit.cshtml
@model NguyenVanHuu0736.Models.NVHStudent

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NVHStudent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NVHStudentId" />
             <div class="form-group">
                <label asp-for="NVHStudentDIACHI" class="control-label"></label>
                <input asp-for="NVHStudentDIACHI" class="form-control" />
                <span asp-validation-for="NVHStudentDIACHI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NVHStudentName" class="control-label"></label>
                <input asp-for="NVHStudentName" class="form-control" />
                <span asp-validation-for="NVHStudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NVHStudentDIACHI" class="control-label"></label>
                <input asp-for="NVHStudentDIACHI" class="form-control" />
                <span asp-validation-for="NVHStudentDIACHI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">QUAY Lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NguyenVanHuu0736/Views/NVHStudent/Index.cshtml
@model IEnumerable<NguyenVanHuu0736.Models.NVHStudent>

@{
    ViewData["Title"] = "Index";
}

<h1></h1>

<p>
    <a asp-action="Create">THÊM MỚI</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NVHStudentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NVHStudentDIACHI)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NVHStudentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NVHStudentDIACHI)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.NVHStudentId">CHỈNH SỬA</a> |
                <a asp-action="Details" asp-route-id="@item.NVHStudentId">CHI TIẾT</a> |
                <a asp-action="Delete" asp-route-id="@item.NVHStudentId">XÓA</a>
            </td>
        </tr>
}
    </tbody>
</table>

NguyenVanHuu0736/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NguyenVanHuu0736</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NguyenVanHuu0736.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NguyenVanHuu0736</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NVHStudent" asp-action="Index">Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NguyenVanHuu0736 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>